name: Check binary
on:
  workflow_call:
    inputs:
      executable:
        required: True
        type: string
    secrets:
      GIT_SSH_PRIVATE_KEY:
        required: true
jobs:
    check-compilation:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Branch
            uses: actions/checkout@v4
          - name: Compile Repo
            run:  |
              sudo apt-get update
              sudo apt-get install -y \
                libx11-dev \
                libxrandr-dev \
                libxcursor-dev \
                libxi-dev \
                libxext-dev \
                libxinerama-dev \
                libgl1-mesa-dev \
                libudev-dev \
                libopenal-dev \
                libvorbis-dev \
                libsfml-dev \
                libfreetype6-dev \
                libflac-dev
              ./build.sh
          - name: Check binary presence
            run: |
                if [ ! -f ./${{ inputs.executable }} ]; then
                    echo "::error title=Binary
                    ERROR::Binary not found"
                    exit 1
                fi
                exit 0

